baseurl = "https://zsdycs.cn"
languageCode = "zh-cn"
title = "执手对影成双 | pengkun Lee"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = "zsdycs"
ignoreFiles = []
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
  self-talking = "/self-talking/:year/:month/:day/:slug/"

[[menu.main]]
    name = "博客"
    url = "/self-talking/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2

[[menu.about]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.about]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.about]]
    name = "简历"
    url = "/vitae/"
    weight = 3

[[menu.vitae]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.vitae]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.vitae]]
    name = "简历"
    url = "/vitae/"
    weight = 3

[[menu.self-talking]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.self-talking]]
    name = "博客"
    url = "/self-talking/"
    weight = 2
[[menu.self-talking]]
    name = "食物"
    url = "/cate/"
    weight = 3
[[menu.self-talking]]
    name = "音乐"
    url = "/music/"
    weight = 4

[[menu.cate]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.cate]]
    name = "博客"
    url = "/self-talking/"
    weight = 2
[[menu.cate]]
    name = "食物"
    url = "/cate/"
    weight = 3
[[menu.cate]]
    name = "音乐"
    url = "/music/"
    weight = 4

[[menu.music]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.music]]
    name = "博客"
    url = "/self-talking/"
    weight = 2
[[menu.music]]
    name = "食物"
    url = "/cate/"
    weight = 3
[[menu.music]]
    name = "音乐"
    url = "/music/"
    weight = 4

[params]
    description = "Personal website of Pengkun Lee; 李鹏坤的个人网站"
    disqusURL = "http://zsdycs.cn"
    footer = "&copy; [执手对影成双](/) 2018 - 2019"
    customJS = ["js/fix-toc.js",
                "js/math-code.js",
                "js/center-img.js",
                "js/right-quote.js",
                "js/no-highlight.js",
                "js/fix-footnote.js",
                "js/external-link.js",
                "js/alt-title.js"]
    author = '李鹏坤'
    githubContentURL = "http://github.com/zsdycs/zsdycs-blog/edit/master/content/"
    edit = "编辑"
    license = "版权"
 [author]
   self-talking= '李鹏坤'