baseurl = "https://zsdycs.cn"
languageCode = "zh-cn"
title = "执手对影成双 | pengkun Lee"
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
disableRSS = true
publishDir = "docs"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "博客"
    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2

[[menu.about]]
    name = "返回"
    url = "/"
    weight = 1
[[menu.about]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.about]]
    name = "简历"
    url = "/vitae/"
    weight = 3

[[menu.vitae]]
    name = "返回"
    url = "/"
    weight = 1
[[menu.vitae]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.vitae]]
    name = "简历"
    url = "/vitae/"
    weight = 3

[[menu.blog]]
    name = "返回"
    url = "/"
    weight = 1
[[menu.blog]]
    name = "博客"
    url = "/blog/"
    weight = 2
[[menu.blog]]
    name = "美食"
    url = "/food/"
    weight = 3

[[menu.food]]
    name = "返回"
    url = "/"
    weight = 1
[[menu.food]]
    name = "博客"
    url = "/blog/"
    weight = 2
[[menu.food]]
    name = "美食"
    url = "/food/"
    weight = 3

[[menu.music]]
    name = "返回"
    url = "/"
    weight = 1
[[menu.music]]
    name = "博客"
    url = "/blog/"
    weight = 2
[[menu.music]]
    name = "美食"
    url = "/food/"
    weight = 3

[params]
    description = "zsdycs; 执手对影成双; Personal website of Pengkun Lee; 李鹏坤的个人网站"
    footer = "&copy; [执手对影成双](/) 2018 - 2020"
    customJS = [
                "js/get-url-relative-path.js",
                "js/darkmode-js.min.js",
                "js/darkmode.js",
                "js/fix-toc.js",
                "js/math-code.js",
                "js/center-img.js",
                "js/right-quote.js",
                "js/no-highlight.js",
                "js/fix-footnote.js",
                "js/external-link.js",
                "js/alt-title.js",
                "js/utteranc.js"
                ]
    author = '李鹏坤'
    githubContentURL = "http://github.com/zsdycs/zsdycs.cn/edit/master/content/"
    edit = "编辑"
    license = "版权"
 [author]
    blog= '李鹏坤'
