baseurl = "https://zsdycs.cn"
languageCode = "zh-cn"
title = "执手对影成双"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = "zsdycs"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
  self-talking = "/self-talking/:year/:month/:day/:slug/"

[[menu.main]]
    name = "碎碎"
    url = "/self-talking/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2

[[menu.self-talking]]
    name = "封面"
    url = "/"
    weight = 1
[[menu.self-talking]]
    name = "碎碎"
    url = "/self-talking/"
    weight = 2
[[menu.self-talking]]
    name = "食物"
    url = "/cate/"
    weight = 3
[[menu.self-talking]]
    name = "音乐"
    url = "/music/"
    weight = 4

[[menu.cate]]
    name = "封面"
    url = "/"
    weight = 1
[[menu.cate]]
    name = "碎碎"
    url = "/self-talking/"
    weight = 2
[[menu.cate]]
    name = "食物"
    url = "/cate/"
    weight = 3
[[menu.cate]]
    name = "音乐"
    url = "/music/"
    weight = 4

[[menu.music]]
    name = "封面"
    url = "/"
    weight = 1
[[menu.music]]
    name = "碎碎"
    url = "/self-talking/"
    weight = 2
[[menu.music]]
    name = "食物"
    url = "/cate/"
    weight = 3
[[menu.music]]
    name = "音乐"
    url = "/music/"
    weight = 4

[params]
    description = "Personal website of Pengkun Lee; 李鹏坤的个人网站"
    disqusURL = "http://zsdycs.cn"
    footer = "![cc0](https://s2.ax1x.com/2019/01/23/kVycxf.png) [执手对影成双](https://zsdycs.cn) 2018 - 2019"
    customJS = ["js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js", "js/external-link.js", "js/alt-title.js"]


  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"


 